### ISSUE TITLE
Didn't work on my old 3DS ver. 4.2.0-9U

### ISSUE THREAD

**Issue by FannyHarsono** [Pirater12/otherapp#2]
Sorry, i tried to launch it but it said error and forced my 3ds to restart..
I am using old 3DS with FW 4.2

I follow the instruction from this website.. 
https://3ds.hacks.guide/installing-boot9strap-(soundhax)

Really sorry to bother you :').. But please help.. Thank you before :)

![IMG_9903](https://user-images.githubusercontent.com/64945974/81257452-8111b100-905d-11ea-9179-08c01a9d62f3.jpeg)
![IMG_9904](https://user-images.githubusercontent.com/64945974/81257482-97b80800-905d-11ea-814c-2048a1f3a941.jpg)
![IMG_9905](https://user-images.githubusercontent.com/64945974/81257499-a0a8d980-905d-11ea-882a-381e241af616.jpg)

**Comment by hax0kartik** [comment]
Hey, you can update your 3ds to the the latest version and then follow the instructions on this page https://3ds.hacks.guide/installing-boot9strap-(usm)

**Comment by FannyHarsono** [comment]
Okay i ended up using the browser method..
https://3ds.hacks.guide/installing-boot9strap-(browser).html

Thank you very much for your help :) !
